# -*- coding: utf-8 -*-
"""Pandas 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5qibtjBJurjV-TCyGp8jSt5-WwTt1xs
"""

!pip install pandas

import pandas as pd

import pandas as pd

encuesta = pd.DataFrame(
    {
        "Julia": ["me gusto", "Fue horrible"],
        "Pedro": ["Fue delicioso", "No estuvo tan mal"],
    },
    index=["Restaurante_1", "Restaurante 2"]
)

encuesta

"""## Cargar Archivos CSV en un dataframe"""

#Leer archivos csv
miCSV= pd.read_csv("DATOS.csv")
miCSV.shape
miCSV.head()

miTitanic=pd.read_csv("archive.zip")
miTitanic.shape
miTitanic.head()

miTitanicFiltrado= miTitanic[miTitanic["Survived"]==0]
miTitanicFiltrado.count()

#Sumar todos los sobrevivientes del titanic

miTitanicFiltrado= miTitanic[miTitanic["Survived"]> 0]
miTitanicFiltrado.count()

miTitanicFiltrado = miTitanic[miTitanic["Survived"] == 1]
miTitanicFiltrado.sum()

MiNetflix=pd.read_csv("Netflix.csv.zip")
MiNetflix.shape
MiNetflix.head()

"""## .describe
Nos muestra los datos estadisticos

"""

MiNetflix.describe()

"""#Selecccinar filas especificas
Filtrar filas

"""

misPeliculas=pd.read_csv("IMDb.csv")